MODEL:
  TYPE: lenet_bn
  NUM_CLASSES: 10
  LOSS_FUN: cross_entropy
OPTIM:
  BASE_LR: 0.1
  METHOD: sgd
  LR_POLICY: cos
  MAX_EPOCH: 20
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
  PARAMS: default
TRAIN:
  DATASET: mnist
  SPLIT: train
  BATCH_SIZE: 512
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 10
TEST:
  DATASET: mnist
  SPLIT: test
  BATCH_SIZE: 512
NUM_GPUS: 1
LOG_PERIOD: 100
DATA_LOADER:
  NUM_WORKERS: 4
