MODEL:
  TYPE: lenet_revgrad
  NUM_CLASSES: 10
  LOSS_FUN: cross_entropy
OPTIM:
  BASE_LR: 0.0001
  METHOD: adam
  LR_POLICY: cos
  MAX_EPOCH: 20
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
  PARAMS: default
TRAIN:
  DATASET: svhn
  SPLIT: train+extra
  BATCH_SIZE: 128
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 100
  LOAD_STRICT: False
  FEEDBACK: RevGrad
  WEIGHTS: /home/dqwang/Work/CLS/LeNetBN_1gpu_svhn_extra_e20.pyth
TEST:
  DATASET: mnist
  SPLIT: test
  BATCH_SIZE: 512
NUM_GPUS: 1
LOG_PERIOD: 500
DATA_LOADER:
  NUM_WORKERS: 4
