MODEL:
  TYPE: resnet
  DEPTH: 26
  WIDTH: 1
  NUM_CLASSES: 10
  LOSS_FUN: cross_entropy
RESNET:
  NORM_FUNC: AdaptBN
  TRANS_FUN: basic_transform
BN:
  USE_PRECISE_STATS: True
  NUM_SAMPLES_PRECISE: 1024
OPTIM:
  BASE_LR: 0.001
  METHOD: adam
  LR_POLICY: cos
  MAX_EPOCH: 1
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
  PARAMS: only_bn_with_affine
TRAIN:
  DATASET: mnist
  SPLIT: test
  BATCH_SIZE: 128
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 10
  FEEDBACK: MinEntropy
  LOAD_STRICT: False
  WEIGHTS: /home/dqwang/Work/CLS/R26w1_1gpu_svhn_extra_e20.pyth
TEST:
  DATASET: mnist
  SPLIT: test
  BATCH_SIZE: 512
NUM_GPUS: 1
LOG_PERIOD: 100
DATA_LOADER:
  NUM_WORKERS: 4
