MODEL:
  TYPE: resnet
  DEPTH: 26
  WIDTH: 1
  NUM_CLASSES: 10
  LOSS_FUN: softmax_entropy_semi
  SEMI_ENTROPY_WEIGHT: 1.0
OPTIM:
  BASE_LR: 0.0001
  METHOD: adam
  LR_POLICY: cos
  MAX_EPOCH: 1
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.00005
  PARAMS: default
TRAIN:
  DATASET: svhn
  SPLIT: train+extra
  BATCH_SIZE: 128
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 10
  FEEDBACK: SemiEnt
  LOAD_STRICT: True
  WEIGHTS: R26w1_1gpu_svhn_extra_e20.pyth
TEST:
  DATASET: mnist
  SPLIT: test
  BATCH_SIZE: 128
NUM_GPUS: 1
LOG_PERIOD: 100
DATA_LOADER:
  NUM_WORKERS: 4
