MODEL:
  TYPE: resnetRG
  DEPTH: 26
  WIDTH: 4
  NUM_CLASSES: 10
  LOSS_FUN: cross_entropy
  REV_GRAD_ALPHA: 1.0
RESNET:
  NORM_FUNC: BN
  TRANS_FUN: basic_transform
BN:
  USE_PRECISE_STATS: True
  NUM_SAMPLES_PRECISE: 1024
OPTIM:
  BASE_LR: 0.0001
  METHOD: adam
  LR_POLICY: constant
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
  PARAMS: default
TRAIN:
  DATASET: svhn
  SPLIT: train+extra
  BATCH_SIZE: 128
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 100
  FEEDBACK: RevGrad
  LOAD_STRICT: False
  WEIGHTS: R26w1_1gpu_svhn_extra_e20.pyth
TEST:
  DATASET: mnist
  SPLIT: test
  BATCH_SIZE: 128
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
