MODEL:
  TYPE: resnet
  DEPTH: 50
  NUM_CLASSES: 1000
  LOSS_FUN: softmax_entropy
RESNET:
  TRANS_FUN: bottleneck_transform
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 64
  STRIDE_1X1: False
  NORM_FUNC: AdaptBN
OPTIM:
  BASE_LR: 0.00025
  METHOD: sgd
  LR_POLICY: cos
  MAX_EPOCH: 1
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  PARAMS: bn_related
AUG:
  TYPE: test
  IMG_FMT: BGR
TRAIN:
  DATASET: imagenet
  SPLIT: val
  CORRUPTION: gaussian_noise
  LEVEL: 5
  IM_SIZE: 256
  BATCH_SIZE: 64
  EVAL_PERIOD: 1
  LOAD_STRICT: False
  WEIGHTS: checkpoints/R-50-1x64d_dds_8gpu.pyth
  ADAPTATION: min_entropy
TEST:
  DATASET: imagenet
  SPLIT: val
  CORRUPTION: gaussian_noise
  LEVEL: 5
  IM_SIZE: 256
  BATCH_SIZE: 256
  WEIGHTS: checkpoints/R-50-1x64d_dds_8gpu.pyth
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
