MODEL:
  TYPE: resnet
  DEPTH: 26
  WIDTH: 1
  NUM_CLASSES: 10
  LOSS_FUN: softmax_entropy
RESNET:
  NORM_FUNC: AdaptBN
  TRANS_FUN: basic_transform
OPTIM:
  BASE_LR: 0.001
  METHOD: adam
  LR_POLICY: cos
  MAX_EPOCH: 1
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
  PARAMS: bn_related
TRAIN:
  DATASET: mnist
  SPLIT: test
  BATCH_SIZE: 128
  EVAL_PERIOD: 1
  LOAD_STRICT: False
  WEIGHTS: checkpoints/R-26_w1_1gpu_svhn_extra_bn.pyth
  ADAPTATION: min_entropy
TEST:
  DATASET: mnist
  SPLIT: test
  BATCH_SIZE: 512
NUM_GPUS: 1
LOG_PERIOD: 100
DATA_LOADER:
  NUM_WORKERS: 4
