MODEL:
  TYPE: resnet
  DEPTH: 26
  WIDTH: 1
  NUM_CLASSES: 10
RESNET:
  NORM_FUNC: BN
  TRANS_FUN: basic_transform
BN:
  USE_PRECISE_STATS: True
  NUM_SAMPLES_PRECISE: 1024
OPTIM:
  BASE_LR: 0.001
  METHOD: adam
  LR_POLICY: cos
  MAX_EPOCH: 1
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
TRAIN:
  DATASET: mnist
  SPLIT: test
  BATCH_SIZE: 128
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 10
  LOAD_STRICT: False
  WEIGHTS: checkpoints/R-26_w1_1gpu_svhn_extra_bn.pyth
  ADAPTATION: test_only
TEST:
  DATASET: mnist
  SPLIT: test
  BATCH_SIZE: 512
  WEIGHTS: checkpoints/R-26_w1_1gpu_svhn_extra_bn.pyth
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
