MODEL:
  TYPE: resnet
  DEPTH: 26
  WIDTH: 1
  NUM_CLASSES: 10
  LOSS_FUN: cross_entropy
RESNET:
  NORM_FUNC: BN
  TRANS_FUN: basic_transform
BN:
  USE_PRECISE_STATS: True
  NUM_SAMPLES_PRECISE: 1024
OPTIM:
  BASE_LR: 0.1
  METHOD: sgd
  LR_POLICY: cos
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
  PARAMS: default
TRAIN:
  DATASET: svhn
  SPLIT: train+extra
  BATCH_SIZE: 512
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 10
TEST:
  DATASET: svhn
  SPLIT: test
  BATCH_SIZE: 512
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
