MODEL:
  TYPE: resnet
  DEPTH: 26
  WIDTH: 4
  NUM_CLASSES: 10
  LOSS_FUN: softmax_entropy
RESNET:
  NORM_FUNC: AdaptBN
  TRANS_FUN: basic_transform
OPTIM:
  BASE_LR: 0.001
  METHOD: adam
  LR_POLICY: cos
  MAX_EPOCH: 1
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0001
  PARAMS: bn_related
TRAIN:
  DATASET: cifar10
  SPLIT: test
  CORRUPTION: gaussian_noise
  LEVEL: 5
  BATCH_SIZE: 512
  IM_SIZE: 32
  EVAL_PERIOD: 1
  LOAD_STRICT: False
  WEIGHTS: checkpoints/R-26_w4_1gpu_cifar10_bn.pyth
  ADAPTATION: min_entropy
TEST:
  DATASET: cifar10
  SPLIT: test
  CORRUPTION: gaussian_noise
  LEVEL: 5
  BATCH_SIZE: 200
  IM_SIZE: 32
  WEIGHTS: checkpoints/R-26_w4_1gpu_cifar10_bn.pyth
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
