MODEL:
  TYPE: san
  WIDTH: 1
  NUM_CLASSES: 100
SAN:
   LAYERS: [2, 1, 2, 4, 1]
   KERNELS: [3, 7, 7, 7, 7]
   SA_TYPE: 0
   NORM_FUNC: BN
BN:
  USE_PRECISE_STATS: True
  NUM_SAMPLES_PRECISE: 1024
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: cos
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
AUG:
  TYPE: original
TRAIN:
  DATASET: cifar100
  SPLIT: train
  BATCH_SIZE: 128
  IM_SIZE: 32
  EVAL_PERIOD: 1
TEST:
  DATASET: cifar100
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 32
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
